### PR TITLE
Add cache for home page and remove cookies.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
Consider this a draft until falcon is updated with cache support. However, you may benefit from it via cloudflare's cache. I don't know what other pages could benefit from cache. What controller should we modify next?

**Comment by ioquatix** [comment]
@nateberkopec would love to have your feedback on this, I'm not much of a rails dev.

**Comment by nateberkopec** [comment]
Oh hey @ioquatix for some reason I didn't see your initial ping.

30 minute HTTP cache on most resources seems pretty prudent. Checked prod and it looks like it's working.

**Comment by ioquatix** [comment]
@nateberkopec thanks for checking it in production it's great to have more eyeballs on stuff like this :)

**Pull request merged**
