### PR TITLE
Add dark mode toggle

### PR DESCRIPTION
**Pull request by JuanitoFatas**
## Summary

This Pull Request adds a dark mode switcher in the center of page top. The switcher defaults to user‘s system setting. Once toggled will store preference in the `Window.localStorage`. 

The switcher (a checkbox) is added next to the body so we can use sibling `~` and scss ampersand selectors to target specific elements. A `.main-container` also added in order to apply styles on home page and other pages.

Implements #290.

## Screenshots 

| mobile light | mobile dark |
| ----------- | ------------- |
|  スクリーンショット 2020-02-19 13 42 34 | スクリーンショット 2020-02-19 13 42 41 |

### Videos

- [dark](https://www.dropbox.com/s/5cir6ucpzm2owtt/dark.mov?dl=0)
- [switcher](https://www.dropbox.com/s/wke3tyq2ybpmyi9/darkmode-switcher.mov?dl=0)
- [light](https://www.dropbox.com/s/rv6hcz3eq8g14wg/light.mov?dl=0)

## Review

- The name of css classes
- If you want to try at local
  Checkout this branch. Start the server. Browse through pages, search something, hover on elements. See if anything looks inconsistent with https://rubyapi.org/. Click dark mode toggle, Browse through pages, search something, hover on elements. See if anything looks inconsistent with dark mode on https://rubyapi.org.

## Downside

- The switcher occupied `1rem` space on top.
- All color changes in the future need to follow this way (add a class then write css for light and dark mode respectively)

### CODE REVIEW

**Comment by ioquatix** [comment]
Is this to make up for lack of browser support?

**Comment by JuanitoFatas** [comment]
> Is this to make up for lack of browser support?

https://twitter.com/arefiev/status/1227902424888881155

Browser support is at [78%](https://caniuse.com/#feat=prefers-color-scheme). 

I think this Pull Request is to give users an option to opt-in / opt-out. Some examples:

Users may not know how to turn on dark mode.
Users prefer light mode for their system UI, but want to browse the docs in dark mode.
Users prefer dark mode for their system UI, but want to browse web pages in light mode.

**Comment by ioquatix** [comment]
Do other websites with dark mode have a toggle like this.

**Comment by AlexWayfer** [comment]
> Do other websites with dark mode have a toggle like this?

Twitter, website:

image

In mobile there was simple toggle:

image

Then like Moon:

image

Now it's like bulb (with or without light):

image

What else… GitHub has no dark theme, GitLab too, Twitch!

image

YouTube (only in Premium, as I know):

image

image

**Comment by AlexWayfer** [comment]
TBH, I thinks it's better to place monochrome icon alongside GitHub icon, Ruby version drop-down, etc.

I know, this approach is quirky by using `checkbox:checked` in CSS, but you're anyway write JavaScript to save it. Maybe it should be inside `body` (header) and toggle a class for it.

**Comment by colby-swandale** [comment]
apologies for not leaving a review yet, this week has just been super busy. I'll try and get time to look at this in the next few days.

**Comment by colby-swandale** [comment]
Hey @JuanitoFatas! Apologies for taking so long to review the PR 😞. I think this is a great first step and have some feedback:

* I agree with @AlexWayfer's comment about adding an icon along side the Github/Version selector buttons. I think it would look a lot cleaner and consistent. But this may not all fit neatly on mobile devices, so we may need to look into adding a sidebar that the user can toggle to fit everything. Would you like to pair on adding that?

* I would like to avoid writing as much CSS as possible, could we leverage tailwindcss libraries https://github.com/hawezo/tailwindcss-theming to provide theme capabilities that can be toggled?

Let me know if you have any questions or if you would like to sit down and pair on this together.

Thank you for your work! 👏

**Comment by AlexWayfer** [comment]
I want this feature too, so I can try to help with this PR, if you wish, @JuanitoFatas. :raised_hands:

**Comment by JuanitoFatas** [comment]
Thanks for the suggestions! I‘ll take another stab this weekend.

**Comment by JuanitoFatas** [comment]
closing this in favor of #323.

**Pull request closed without merging**
