### PR TITLE
Patches for Dark mode V2

### PR DESCRIPTION
**Pull request by AlexWayfer**
1.  Leave red header for dark theme.
2.  Replace Unicode symbols with Font Awesome icons.

### CODE REVIEW

**Comment by colby-swandale** [comment]
👋 Thanks for the PR. I've merged the font-awesome icon for theme switching as part of my changes to #323 which is now in master.

Thanks!

**Comment by AlexWayfer** [comment]
>  Thanks for the PR. I've merged the font-awesome icon for theme switching as part of my changes to #323 which is now in master.
> 
> Thanks!

What about read header for dark theme?

**Comment by AlexWayfer** [comment]
@colby-swandale ?

**Comment by colby-swandale** [comment]
Hey sorry for not getting back to you, i dropped the ball on this in not giving an explanation on why i didn't include it.

The main reason was that i found the red color didn't fit into the dark color scheme and was contrasting the grey background in an unideal way that i found to be distracting. Too be fair i have this same issue with the light mode as well and have been trying to think of ways on how to resolve that, but the red in the dark mode really showed this issue.

When i put together the dark mode color schema, i wanted a set of colors which followed the general guidelines like:

* https://uxdesign.cc/dark-mode-ui-design-the-definitive-guide-part-1-color-53dcfaea5129
* https://material.io/design/color/dark-theme.html
* https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/
* https://blog.prototypr.io/how-to-design-a-dark-theme-for-your-android-app-3daeb264637

In particular, i followed pretty closely the idea of having a base color that would incrementally get lighter based on the app UI hierarchy and decided on the grey that's currently on the theme.

I hope that explains things and sorry again for not including this explanation when i closed the PR.

**Comment by AlexWayfer** [comment]
@colby-swandale as I see in referenced guidelines, I think we can make logo red for dark theme, what do you think?

**Comment by colby-swandale** [comment]
Making the logo red in dark mode has the opposite effect of not having enough contrast & being hard to read.

Screen Shot 2020-08-19 at 9 34 52 am

**Pull request closed without merging**
