### PR TITLE
Add StandardRB instructions to the README

### PR DESCRIPTION
**Pull request by natematykiewicz**

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Thank you.

Maybe this place is not too relevant, but maybe somebody can help:

If I'm using an editor plugin like this one: https://atom.io/packages/linter-rubocop

Can I somehow integrate it with `standard` in this repository?

I have `bundle exec rubocop` command for any project, so linting in editor depends on `.rubocop.yml` in a project, but with `standard` there is no local RuboCop config.

**Comment by natematykiewicz** [comment]
@AlexWayfer I don't use Atom, but hopefully this helps you! It sounds like you've got most of it set up already. https://github.com/testdouble/standard/wiki/IDE:-Atom

**Comment by natematykiewicz** [comment]
I updated the documentation to mention how to integrate StandardRB into your editor, since the question was asked here.

**Comment by AlexWayfer** [comment]
@natematykiewicz thank you!

**Comment by natematykiewicz** [comment]
@AlexWayfer You're welcome! Did the instructions work for you?

**Comment by AlexWayfer** [comment]
> @AlexWayfer You're welcome! Did the instructions work for you?

It must work, but I don't want to test (change the command), because it affects all projects in the editor. I'll wait for something like https://github.com/AtomLinter/linter-rubocop/issues/407

**Comment by colby-swandale** [comment]
Thanks!

**Pull request merged**
