### PR TITLE
Refactor nav header

### LINKED ISSUE #291: Listing of Methods Visible on Mobile
I'd like to request that Ruby API's web interface expose a listing of methods for a particular class.

I realise that to some extent this is an aesthetic decision and reasonable people may disagree. My argument would be that users may sometimes have an inkling of what they're looking for but nevertheless find it useful to quickly see the list of available methods. At the moment, the options are to search (which can be frustrating if you don't pick the correct wording) or to scan the documentation for a class (which can be time-consuming in big classes).

On mobile, it would most likely make sense to have this listing hidden behind some kind of menu.

### PR DESCRIPTION
**Pull request by colby-swandale**
This PR refactors the navigation to allow mobile users to perform the same options as desktop users, ie: Toggle theme & select Ruby Version.

Some things I still want to do:

* Nice transitions when opening/closing the mobile menu
* Hide mobile menu when the user taps outside the nav.

Supersedes #389 

Closes #291 

Screenshots:

Sizzy-iPhone 12 localhost 11May 23 37-1

Sizzy-iPhone 12 localhost 11May 23 37-2

Sizzy-iPhone 12 localhost 11May 23 37

Sizzy-iPhone 12 localhost 11May 23 39-1

Sizzy-iPhone 12 localhost 11May 23 39

Sizzy-iPhone 12 localhost 11May 23 40

### CODE REVIEW

**Comment by AlexWayfer** [comment]
I don't understand what is on 1st and 5th screenshots, there is a bar with cross like menu is expanded but without menu itself.

**Comment by natematykiewicz** [comment]
> I don't understand what is on 1st and 5th screenshots, there is a bar with cross like menu is expanded but without menu itself.

I think the bar doesn't expand. It's just that the "object show" page adds in a list of links that's not present on other pages. I haven't read the code yet though.

So screenshot 3 is when you load a page. 6 is the menu expanded on the objects show page. 1 is the menu expanded on all other pages.

**Comment by AlexWayfer** [comment]
> > I don't understand what is on 1st and 5th screenshots, there is a bar with cross like menu is expanded but without menu itself.
> 
> I think the bar doesn't expand. It's just that the "object show" page adds in a list of links that's not present on other pages. I haven't read the code yet though.
> 
> So screenshot 3 is when you load a page. 6 is the menu expanded on the objects show page. 1 is the menu expanded on all other pages.

Oh, OK, I got it, thanks.

**Comment by colby-swandale** [comment]
@AlexWayfer @natematykiewicz Did you have any feedback about the design/UI? I'm keen to get this merged.

**Comment by natematykiewicz** [comment]
I haven't pulled it up to "feel" it, but the screenshots seem good and intuitive to me. I think the only reason there was confusion in this thread is because the order the screenshots were uploaded in isn't the order you'd actually experience the site in.

Ship it! 🚀

**Comment by colby-swandale** [comment]
Thanks for the feedback. Next time I'll be sure to make it a lot more clearer.

**Comment by natematykiewicz** [comment]
I see you deployed it. Feels good to me. Nice work!

**Comment by AlexWayfer** [comment]
I confused with at least 2 things:
1. Buttons (logo and menu/close) are in different places: https://drive.google.com/file/d/10xt15W-4RyW0TOkeO_FEYyIwfqlXKsjO/view?usp=sharing
2. The popup with methods take only around a half of screen height and not closing via a tap outside of it.

Also I'm not sure what to do with #389 now.

**Comment by natematykiewicz** [comment]
Perhaps the logo and hamburger should be moved so they're directly under where the menu shows them, so they don't shift around?

**Comment by natematykiewicz** [comment]
I've also noticed the sun/moon is a little low. It's not quite vertically centered.

**Pull request merged**
